name: scrapper
channels:
  - defaults
dependencies:
  - bs4=4.11.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - charset-normalizer=2.0.4
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pycparser=2.21
  - python=3.10.9
  - readline=8.2
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - beautifulsoup4==4.11.1
      - brotlipy==0.7.0
      - certifi==2022.12.7
      - cffi==1.15.1
      - cryptography==39.0.1
      - pip==23.0.1
      - pyopenssl==23.0.0
      - pysocks==1.7.1
      - requests==2.28.1
      - setuptools==65.6.3
      - soupsieve==2.3.2.post1
      - urllib3==1.26.14
      - wheel==0.38.4
      - googletrans==3.1.0a0
